train_file: ['/home/zhengf_lab/cse12032460/ld/data/data_json/nlvr_train.json']
val_file: ['/home/zhengf_lab/cse12032460/ld/data/data_json/nlvr_dev.json']                  
test_file: ['/home/zhengf_lab/cse12032460/ld/data/data_json/nlvr_test.json']  

image_root: '/home/zhengf_lab/cse12032460/ld/data/NLVR2' 

image_res: 384
batch_size: 16 

bert_config: '/home/zhengf_lab/cse12032460/ld/multimodal_models/ALBEF_sammy/configs/config_bert.json'

alpha: 0.4
distill: True
warm_up: True
eval_ema: False

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







