train_file: ['/home/zhengf_lab/cse30008213/ld/data/data_json/vqa_train.json',
             '/home/zhengf_lab/cse30008213/ld/data/data_json/vqa_val.json',   
             '/home/zhengf_lab/cse30008213/ld/data/data_json/vg_qa.json']
             
test_file: ['/home/zhengf_lab/cse30008213/ld/data/data_json/vqa_test.json']
answer_list: '/home/zhengf_lab/cse30008213/ld/data/data_json/answer_list.json'

vqa_root: '/home/zhengf_lab/cse30008213/ld/data/COCO2014/' #train2014/
vg_root: '/home/zhengf_lab/cse30008213/ld/data/VisualGenome/'  #image/

image_res: 384
batch_size_train: 32 
batch_size_test: 16 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: '/home/zhengf_lab/cse30008213/ld/multimodal_models/ALBEF_sammy/configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







